using ConcernsCaseWork.API.Contracts.RequestModels.TrustFinancialForecasts;
using ConcernsCaseWork.API.Contracts.ResponseModels.TrustFinancialForecasts;

namespace ConcernsCaseWork.Service.TrustFinancialForecast;

public interface ITrustFinancialForecastService
{
	Task<string> CreateTrustFinancialForecast(CreateTrustFinancialForecastRequest request);
	Task<TrustFinancialForecastResponse> GetTrustFinancialForecastById(GetTrustFinancialForecastRequest request);
	Task UpdateTrustFinancialForecast(UpdateTrustFinancialForecastRequest request);
}