

// Code scaffolded by EF Core assumes nullable reference types (NRTs) are not used or disabled.
// If you have enabled NRTs for your project, then un-comment the following line:
// #nullable disable

namespace Concerns.Data.Models
{
    public partial class ViewAcademyConversions
    {
        public string PRid { get; set; }
        public string Rid { get; set; }
        public string GeneralDetailsUrn { get; set; }
        public string GeneralDetailsLaestab { get; set; }
        public string GeneralDetailsProjectName { get; set; }
        public string GeneralDetailsAcademyUrn { get; set; }
        public string GeneralDetailsAcademyLaestab { get; set; }
        public string GeneralDetailsAcademyUkprn { get; set; }
        public string GeneralDetailsAcademyName { get; set; }
        public string GeneralDetailsInterestStatus { get; set; }
        public string GeneralDetailsProjectStatus { get; set; }
        public string GeneralDetailsAcademyStatus { get; set; }
        public string GeneralDetailsDAoProgress { get; set; }
        public string GeneralDetailsStage { get; set; }
        public string GeneralDetailsRouteOfProject { get; set; }
        public DateTime? GeneralDetailsExpectedOpeningDate { get; set; }
        public DateTime? GeneralDetailsActualDateOpened { get; set; }
        public DateTime? GeneralDetailsReBrokeredDate { get; set; }
        public string GeneralDetailsLocalAuthority { get; set; }
        public string GeneralDetailsRscRegion { get; set; }
        public string GeneralDetailsPhase { get; set; }
        public string GeneralDetailsGrade6 { get; set; }
        public string GeneralDetailsTeamLeader { get; set; }
        public string GeneralDetailsProjectLead { get; set; }
        public string GeneralDetailsDivisionalLead { get; set; }
        public string GeneralDetailsInterestProjectLead { get; set; }
        public string GeneralDetailsRecordStatus { get; set; }
        public DateTime? InterestDateOfInterest { get; set; }
        public DateTime? InterestResponseToInterestContactDate { get; set; }
        public string InterestComments { get; set; }
        public string InterestContactName { get; set; }
        public string InterestContactPhone { get; set; }
        public string InterestContactEmail { get; set; }
        public string DeliveryProcessRagRating { get; set; }
        public string DeliveryProcessMainIssueForDelay { get; set; }
        public string DeliveryProcessSecondaryIssueForDelay { get; set; }
        public string DeliveryProcessPfi { get; set; }
        public DateTime? DeliveryProcessDateForDiscussionByRscHtb { get; set; }
        public string DeliveryProcessGeneralComments { get; set; }
        public string DeliveryProcessLinkToWorkplaces { get; set; }
        public string DeliveryProcessMainContactForConversion { get; set; }
        public string DeliveryProcessMainContactForConversionName { get; set; }
        public string DeliveryProcessMainContactForConversionEmail { get; set; }
        public string DeliveryProcessMainContactForConversionPhone { get; set; }
        public string DeliveryProcessApplicationFormReference { get; set; }
        public string DeliveryProcessConsideringSoSIebStage { get; set; }
        public DateTime? DeliveryProcessExpectedDateForGb { get; set; }
        public string DeliveryProcessSoSImposedIeb { get; set; }
        public DateTime? DeliveryProcessDateSoSIebIssued { get; set; }
        public DateTime? DeliveryProcessDateLaIebApplicationReceived { get; set; }
        public DateTime? DeliveryProcessDateLaIebApplicationApproved { get; set; }
        public DateTime? DeliveryProcessDateOfInitialMeeting { get; set; }
        public DateTime? DeliveryProcessDateSponsorMatchAgreed { get; set; }
        public DateTime? DeliveryProcessDateDAoDueDiligenceAnnexReceived { get; set; }
        public DateTime? DeliveryProcessDateChurchFoundationConsultationReceived { get; set; }
        public string DeliveryProcessViabilityConcernEffectingSponsorMatch { get; set; }
        public string DeliveryProcessViabilityClosureRoute { get; set; }
        public DateTime? DeliveryProcessDateParentInformedBySponsor { get; set; }
        public DateTime? DeliveryProcessDateForDiscussionByRscHtbForAgreeingPreOpeningGrant { get; set; }
        public DateTime? DeliveryProcessActualDateOfGbResolution { get; set; }
        public DateTime? DeliveryProcessLetterSentWithDtFActionsGbLa { get; set; }
        public string DeliveryProcessDirectionToFacilitateConversion { get; set; }
        public DateTime? DeliveryProcessDateDirectionToFacilitateConversionIssuedGbOrLa { get; set; }
        public string DeliveryProcessEqualityImpactAssessmentsComplete { get; set; }
        public string DeliveryProcessPan { get; set; }
        public DateTime? DeliveryProcessAcknowledgementAndFollowUpSentToSchool { get; set; }
        public string DeliveryProcessGrantPaymentType { get; set; }
        public DateTime? DeliveryProcessGrantPaymentProcessed { get; set; }
        public string DeliveryProcessLand { get; set; }
        public string DeliveryProcessRisksAssociatedToLand { get; set; }
        public string DeliveryProcessArticlesOfAssociations { get; set; }
        public DateTime? DeliveryProcessArticlesOfAssociationsReceivedCleared { get; set; }
        public string DeliveryProcessArticlesOfAssociationRelatedComments { get; set; }
        public string DeliveryProcessFundingAgreement { get; set; }
        public DateTime? DeliveryProcessFundingAgreementReceivedCleared { get; set; }
        public string DeliveryProcessFundingAgreementRelatedComments { get; set; }
        public string DeliveryProcessCommercialTransferAgreement { get; set; }
        public DateTime? DeliveryProcessCommercialTransferAgreementReceivedCleared { get; set; }
        public string DeliveryProcessCommercialTransferAgreementRelatedComments { get; set; }
        public string DeliveryProcessRiskProtectionArrangements { get; set; }
        public string DeliveryProcessReasonForNoRpa { get; set; }
        public DateTime? DeliveryProcessRiskProtectionAgreementStartDate { get; set; }
        public string DeliveryProcessCommentsForOfstedPreOpeningInspection { get; set; }
        public DateTime? DeliveryProcessFundingAgreementConditionsMet { get; set; }
        public DateTime? DeliveryProcessDateSettlementAgreementApproved { get; set; }
        public string DeliveryProcessNumberOfSettlementAgreements { get; set; }
        public string DeliveryProcessTotalAmountPaidToSchoolEmployees { get; set; }
        public string DeliveryProcessDfEEfaContribution { get; set; }
        public string DeliveryProcessOfDfEEfaContributionToTotalPaidToEmployees { get; set; }
        public string DeliveryProcessDidSettlementExceedContractualTerms { get; set; }
        public string DeliveryProcessWhoPaidTheEnhancement { get; set; }
        public DateTime? DeliveryProcessBaselineDate { get; set; }
        public string DeliveryProcessPayRun { get; set; }
        public string ProposedAcademyDetailsNewAcademyName { get; set; }
        public string ProposedAcademyDetailsNewAcademyUrn { get; set; }
        public string ProposedAcademyDetailsAcademyPhaseProposed { get; set; }
        public string ProposedAcademyDetailsAcademyMainContactName { get; set; }
        public string ProposedAcademyDetailsAcademyMainContactRole { get; set; }
        public string ProposedAcademyDetailsAcademyMainContactEmail { get; set; }
        public string ProposedAcademyDetailsAcademyMainContactPhone { get; set; }
        public string ProposedAcademyDetailsAcademyMainContactAddressLine1 { get; set; }
        public string ProposedAcademyDetailsAcademyMainContactAddressLine2 { get; set; }
        public string ProposedAcademyDetailsAcademyMainContactAddressLine3 { get; set; }
        public string ProposedAcademyDetailsAcademyMainContactTown { get; set; }
        public string ProposedAcademyDetailsAcademyMainContactCounty { get; set; }
        public string ProposedAcademyDetailsAcademyMainContactPostcode { get; set; }
        public string ProposedAcademyDetailsAcademyLeadFinanceName { get; set; }
        public string ProposedAcademyDetailsAcademyLeadFinanceEmail { get; set; }
        public string ProposedAcademyDetailsAcademyLeadFinancePhone { get; set; }
        public string ProposedAcademyDetailsAcademySecureAccessContactName { get; set; }
        public string ProposedAcademyDetailsAcademySecureAccessContactEmail { get; set; }
        public string ProposedAcademyDetailsAcademyProposedCapacityPrimaryRYr6 { get; set; }
        public string ProposedAcademyDetailsAcademyProposedCapacitySecondaryYr7Yr11 { get; set; }
        public string ProposedAcademyDetailsAcademyProposedCapacityPost16 { get; set; }
        public string ProposedAcademyDetailsPost16 { get; set; }
        public string ProposedAcademyDetailsGagFundingPupilNumbersType { get; set; }
        public string ProposedAcademyDetailsMatFaClauses3A3FOption1ConvSpons { get; set; }
        public string ProposedAcademyDetailsMatFaClauses3A3FOption2FsNewProv { get; set; }
        public string ProposedAcademyDetailsMatFaClauses3HIfApplicableNotConv { get; set; }
        public string ProposedAcademyDetailsSatFaClauses316321Option1ConvSpons { get; set; }
        public string ProposedAcademyDetailsSatFaClauses316321Option2FsNewProv { get; set; }
        public string ProposedAcademyDetailsSatFaClause323IfApplicableNotConv { get; set; }
        public DateTime? ApprovalProcessApplicationDate { get; set; }
        public DateTime? ApprovalProcessReStartApplicationDate { get; set; }
        public string ApprovalProcessAppliedOrBrokered { get; set; }
        public DateTime? ApprovalProcessDateSubmittedForAoDecision { get; set; }
        public string ApprovalProcessAoDecisionMethod { get; set; }
        public DateTime? ApprovalProcessDateRscHtbApprovalGranted { get; set; }
        public DateTime? ApprovalProcessAoIssuedDate { get; set; }
        public DateTime? ApprovalProcessRevokedDAoDate { get; set; }
        public DateTime? ApprovalProcessDateRscFundingAgreementApprovedInPrinciple { get; set; }
        public DateTime? ApprovalProcessFundingAgreementApprovedDate { get; set; }
        public string EfaFundingUpin { get; set; }
        public DateTime? EfaFundingBankDetailsReceived { get; set; }
        public DateTime? EfaFundingDraftLetterSentDate { get; set; }
        public DateTime? EfaFundingDraftLetterTargetDate { get; set; }
        public string EfaFundingEfaTerritory { get; set; }
        public DateTime? EfaFundingEfaWelcomeLetterAndFinanceLetterSentDate { get; set; }
        public DateTime? EfaFundingExpectedPaymentDate { get; set; }
        public DateTime? EfaFundingFinalFundingLetterSentDate { get; set; }
        public DateTime? EfaFundingFinalFundingLetterTargetDate { get; set; }
        public string EfaFundingSugAvailable { get; set; }
        public DateTime? EfaFundingReminderLetterSentDate { get; set; }
        public string EfaFundingNavCode { get; set; }
        public DateTime? EfaHandoverPdfFaSavedInWorkplace { get; set; }
        public DateTime? EfaHandoverSupportGrantCertificateReceived { get; set; }
        public DateTime? EfaHandoverPreOpeningCertificateReceived { get; set; }
        public DateTime? EfaHandoverFundingAgreementDocumentsRedactedAndSavedInWorkplaces { get; set; }
        public DateTime? EfaHandoverFundingAgreementOnGovUk { get; set; }
        public DateTime? EfaHandoverFundingAgreementToRemoteStorage { get; set; }
        public DateTime? EfaHandoverFundingAgreementCopyToTheTrust { get; set; }
        public string EfaHandoverIssue1RequiringEfaAction { get; set; }
        public string EfaHandoverIssue2RequiringEfaAction { get; set; }
        public string EfaHandoverLiveIssueSComments { get; set; }
        public string EfaHandoverIssue1ToBeAwareOf { get; set; }
        public string EfaHandoverIssue2ToBeAwareOf { get; set; }
        public string EfaHandoverOtherIssueSComments { get; set; }
        public string EfaHandoverSacreExemptionGiven { get; set; }
        public DateTime? EfaHandoverSacreExemptionIssuedOn { get; set; }
        public DateTime? EfaHandoverSacreExemptionExpiryDate { get; set; }
        public string EfaHandoverSacreExemptionRenewalAppliedFor { get; set; }
        public DateTime? EfaHandoverSacreExemptionRenewalApproved { get; set; }
        public DateTime? EfaHandoverSacreExemptionRenewalRejected { get; set; }
        public DateTime? EfaHandoverSacreNewExemptionExpiryDate { get; set; }
        public DateTime? EfaHandoverHandoverCompleteDate { get; set; }
        public string ProjectTemplateInformationAcademicYear { get; set; }
        public string ProjectTemplateInformationFinancialYear { get; set; }
        public string ProjectTemplateInformationViabilityIssue { get; set; }
        public string ProjectTemplateInformationDeficit { get; set; }
        public string ProjectTemplateInformationRelevantDistance { get; set; }
        public string ProjectTemplateInformationProjectManagementForecast { get; set; }
        public string ProjectTemplateInformationEducationAdviceDevelopmentOfEducationalPlanCurriculumStaffingStructureAndPolicies { get; set; }
        public string ProjectTemplateInformationLegalServices { get; set; }
        public string ProjectTemplateInformationCommunicationsAndMarketingSupport { get; set; }
        public string ProjectTemplateInformationConsultationServices { get; set; }
        public string ProjectTemplateInformationHrAndRecruitmentServicesInclTupe { get; set; }
        public string ProjectTemplateInformationFinancialManagementAndAdvice { get; set; }
        public string ProjectTemplateInformationAppointmentOfKeyStaffIncludingPrincipleDesignate { get; set; }
        public string ProjectTemplateInformationFinancialInformationSystems { get; set; }
        public string ProjectTemplateInformationOtherEGIctSystemsProjectContingencyAllocation { get; set; }
        public string ProjectTemplateInformationEigRationale { get; set; }
        public string ProjectTemplateInformationRationaleForProject { get; set; }
        public string ProjectTemplateInformationRationaleForSponsor { get; set; }
        public string ProjectTemplateInformationRisksAndIssues { get; set; }
        public string ProjectTemplateInformationProjectedRevenueBalanceAtYearEnd { get; set; }
        public string ProjectTemplateInformationRevenueDeficitReasonsAndRemedialAction { get; set; }
        public string ProjectTemplateInformationProjectedCapitalBalanceAtYearEnd { get; set; }
        public string ProjectTemplateInformationCapitalDeficitReasonsAndRemedialAction { get; set; }
        public string ProjectTemplateInformationAy1CapacityForecast { get; set; }
        public string ProjectTemplateInformationAy1TotalPupilNumberForecast { get; set; }
        public string ProjectTemplateInformationAy2CapacityForecast { get; set; }
        public string ProjectTemplateInformationAy2TotalPupilNumberForecast { get; set; }
        public string ProjectTemplateInformationAy3CapacityForecast { get; set; }
        public string ProjectTemplateInformationAy3TotalPupilNumberForecast { get; set; }
        public string ProjectTemplateInformationFyTotalAllocationAndIncome { get; set; }
        public string ProjectTemplateInformationFyRevenueGrossExpenditure { get; set; }
        public string ProjectTemplateInformationFyRevenueBalanceInYear { get; set; }
        public string ProjectTemplateInformationFyRevenueBalanceBroughtForward { get; set; }
        public string ProjectTemplateInformationFyRevenueBalanceCarriedForward { get; set; }
        public string ProjectTemplateInformationFy1TotalAllocationAndIncome { get; set; }
        public string ProjectTemplateInformationFy1RevenueGrossExpenditure { get; set; }
        public string ProjectTemplateInformationFy1RevenueBalanceInYear { get; set; }
        public string ProjectTemplateInformationFy1RevenueBalanceBroughtForward { get; set; }
        public string ProjectTemplateInformationFy1RevenueBalanceCarriedForward { get; set; }
        public string ProjectTemplateInformationFy2TotalAllocationAndIncome { get; set; }
        public string ProjectTemplateInformationFy2RevenueGrossExpenditure { get; set; }
        public string ProjectTemplateInformationFy2RevenueBalanceInYear { get; set; }
        public string ProjectTemplateInformationFy2RevenueBalanceBroughtForward { get; set; }
        public string ProjectTemplateInformationFy2RevenueBalanceCarriedForward { get; set; }
        public string OfstedLatestOfstedSection5CategoryOfConcern { get; set; }
        public DateTime? OfstedLatestOfstedSection5DateInCategory4 { get; set; }
        public DateTime? OfstedLatestOfstedSection5InspectionDate { get; set; }
        public string OfstedLatestOfstedSection5OverallEffectiveness { get; set; }
        public string OfstedNumberOfMonthsInCategory4 { get; set; }
        public DateTime? OfstedLatestOfstedSection8InspectionDate { get; set; }
        public string OfstedLatestOfstedSection8Judgement { get; set; }
        public string TrustSponsorManagementSponsor1Provisional { get; set; }
        public string TrustSponsorManagementSponsor1NameProvisional { get; set; }
        public string TrustSponsorManagementSponsor2Provisional { get; set; }
        public string TrustSponsorManagementSponsor2NameProvisional { get; set; }
        public string TrustSponsorManagementSponsor3Provisional { get; set; }
        public string TrustSponsorManagementSponsor3NameProvisional { get; set; }
        public string TrustSponsorManagementTrust { get; set; }
        public string TrustSponsorManagementCoSponsor1 { get; set; }
        public string CoSponsor1 { get; set; }
        public string TrustSponsorManagementCoSponsor1SponsorName { get; set; }
        public string TrustSponsorManagementCoSponsor2 { get; set; }
        public string TrustSponsorManagementCoSponsor2SponsorName { get; set; }
        public string TrustSponsorManagementCoSponsor3 { get; set; }
        public string TrustSponsorManagementCoSponsor3SponsorName { get; set; }
        public string TrustSponsorManagementPreviousTrust { get; set; }
        public string TrustSponsorManagementPreviousTrustName { get; set; }
        public string TrustSponsorManagementPreviousSponsorId { get; set; }
        public string TrustSponsorManagementPreviousSponsorName { get; set; }
        public string CaseDataClosing { get; set; }
        public string CaseDataClosureStatus { get; set; }
        public DateTime? CaseDataDateClosureCommenced { get; set; }
        public string CaseDataProjectProgress { get; set; }
        public DateTime? CaseDataExpectedClosureDate { get; set; }
        public DateTime? CaseDataReBrokeredDateCaseData { get; set; }
        public string CaseDataTrustNotice { get; set; }
        public string CaseDataCurrentKs2Rag { get; set; }
        public string CaseDataCurrentKs4Rag { get; set; }
        public string CaseDataCurrentKs5Rag { get; set; }
        public string CaseDataCurrentConfidenceTerm { get; set; }
        public string CaseDataCurrentKs2ConfidenceMeasure { get; set; }
        public string CaseDataCurrentKs4ConfidenceMeasure { get; set; }
        public string CaseDataStatus { get; set; }
        public DateTime? CaseDataFntlIssued { get; set; }
        public DateTime? CaseDataFntlRemoved { get; set; }
        public string CaseDataEfaRagRating { get; set; }
        public string CaseDataConcernType { get; set; }
        public string CaseDataKs2BelowTheFloor { get; set; }
        public string CaseDataKs4BelowTheFloor { get; set; }
        public string CaseDataKs5BelowTheFloorAcademicCase { get; set; }
        public string CaseDataKs5BelowTheFloorAppliedGeneralCase { get; set; }
        public string CaseDataKs2CoastingAcademy { get; set; }
        public string CaseDataKs4CoastingAcademy { get; set; }
        public string CaseDataEducationAdviserTimingOfNextVisit { get; set; }
        public string CaseDataIncreasedCapacityInTrustGb { get; set; }
        public string CaseDataChangeOfLeadership { get; set; }
        public string CaseDataAcademyContactNumber { get; set; }
        public string CaseDataAcademyHeadPrincipal { get; set; }
        public string CaseDataCommentsNextSteps { get; set; }
        public string CaseDataPlannedAction { get; set; }
        public string CaseDataOtherActionTaken { get; set; }
        public DateTime? CaseDataDateOfInitialContact { get; set; }
        public string CaseDataLinkToWorkplaces { get; set; }
    }
}
