//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConcernsCaseWork.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Home_en {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Home_en() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ConcernsCaseWork.Resources.Pages.Home.en", typeof(Home_en).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Closed cases.
        /// </summary>
        internal static string Button_ClosedCases {
            get {
                return ResourceManager.GetString("Button:ClosedCases", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create case.
        /// </summary>
        internal static string Button_CreateCase {
            get {
                return ResourceManager.GetString("Button:CreateCase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Closed.
        /// </summary>
        internal static string Table_Column_Closed {
            get {
                return ResourceManager.GetString("Table:Column:Closed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created.
        /// </summary>
        internal static string Table_Column_Created {
            get {
                return ResourceManager.GetString("Table:Column:Created", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Case ID.
        /// </summary>
        internal static string Table_Column_ID {
            get {
                return ResourceManager.GetString("Table:Column:ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last update.
        /// </summary>
        internal static string Table_Column_LastUpdate {
            get {
                return ResourceManager.GetString("Table:Column:LastUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Primary case type.
        /// </summary>
        internal static string Table_Column_PrimaryCaseType {
            get {
                return ResourceManager.GetString("Table:Column:PrimaryCaseType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RAG rating.
        /// </summary>
        internal static string Table_Column_RagRating {
            get {
                return ResourceManager.GetString("Table:Column:RagRating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trust/Academy.
        /// </summary>
        internal static string Table_Column_TrustAcademy {
            get {
                return ResourceManager.GetString("Table:Column:TrustAcademy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no cases available..
        /// </summary>
        internal static string Table_EmptyCases {
            get {
                return ResourceManager.GetString("Table:EmptyCases", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your active casework.
        /// </summary>
        internal static string Table_Header_ActiveCases {
            get {
                return ResourceManager.GetString("Table:Header:ActiveCases", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Closed for monitoring.
        /// </summary>
        internal static string Table_Header_MonitoringCases {
            get {
                return ResourceManager.GetString("Table:Header:MonitoringCases", resourceCulture);
            }
        }
    }
}
