name: Validate source branch

on:
  pull_request:
    branches:
      - main

jobs:
  check:
    name: Incoming branch validation
    runs-on: ubuntu-latest
    steps:
      - id: branch
        name: Check branch name
        run: |
          GIT_BRANCH=${{ github.head_ref }}
          if [[ "$GIT_BRANCH" =~ ^hotfix/*|^feature/*|^renovate/* ]];
          then
            echo "'$GIT_BRANCH' is a permitted branch"
            exit 0
          else
            echo "'$GIT_BRANCH' is not a permitted branch"
            exit 1
          fi
