name: Cypress test linting

on:
  pull_request:
    paths:
      - ConcernsCaseWork/ConcernsCaseWork.CypressTests/**/*
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        # Updated to latest v5 SHA
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8
      - name: lint cypress tests
        working-directory: ConcernsCaseWork/ConcernsCaseWork.CypressTests
        run: |
          npm ci
          npm run lint        
