name: .NET

on:
  push:
    branches: [ main ]
  pull_request:

env:
  JAVA_VERSION: '21'
  DOTNET_VERSION: 8.0.x

jobs:
  build-test:
    name: Build and Test
    runs-on: ubuntu-24.04
    services:
      sql-server:
        image: mcr.microsoft.com/mssql/server:2022-latest@sha256:ea73825f3d88a23c355ac2f9fdc6bd960fec90171c12c572109b36a558f77bb8
        ports:
        - 1433:1433
        env:
          ACCEPT_EULA: Y
          SA_PASSWORD: P1swrd!$
    steps:
      - name: Start Redis
        run: |
          docker run -d --rm \
            -p 6379:6379 \
            --health-cmd "redis-cli ping" \
            --health-interval "10s" \
            --health-timeout "5s" \
            --health-retries "5" \
            --env GITHUB_ACTIONS=true \
            --env CI=true \
            --name redis \
            redis:6-alpine \
            redis-server --requirepass "my-secureP@SS1"

      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
        with:
          fetch-depth: 0 # Shallow clones disabled for a better relevancy of SC analysis

      - name: Check appsettings validity
        run: |
          DIRECTORY=./ConcernsCaseWork/ConcernsCaseWork
          for i in "$DIRECTORY"/appsettings*.json; do
            echo "$i" && jq . "$i"
          done

      - name: Setup .NET ${{ env.DOTNET_VERSION }}
        uses: actions/setup-dotnet@67a3573c9a986a3f9c594539f4ab511d57bb3ce9 # v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Set up JDK ${{ env.JAVA_VERSION }}
        uses: actions/setup-java@c5195efecf7bdfc987ee8bae7a71cb8b11521c00 # v4
        with:
          distribution: 'microsoft'
          java-version: ${{ env.JAVA_VERSION }}

      - name: Cache SonarCloud packages
        uses: actions/cache@5a3ec84eff668545956fd18022155c47e93e2684 # v4
        with:
          path: ~\sonar\cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar

      - name: Install SonarCloud tools
        run: |
          dotnet tool install --global dotnet-sonarscanner
          dotnet tool install --global dotnet-reportgenerator-globaltool

      - name: Add nuget package source
        run: dotnet nuget add source --username USERNAME --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/DFE-Digital/index.json"

      - name: Build solution, test and run SonarCloud scanner
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          # Note: The database name may be overridden by the tests
          VCAP_SERVICES: "{'redis': [{'credentials': {'host': 'localhost','password': 'my-secureP@SS1','port': '6379','tls_enabled': 'true'}}]}"
          ConnectionStrings__DefaultConnection: 'Server=localhost,1433;Database=integrationtests;User Id=sa;Password=P1swrd!$;TrustServerCertificate=True'
        run: |
          dotnet-sonarscanner begin /d:sonar.qualitygate.wait=true /d:sonar.scanner.skipJreProvisioning=true /k:"DFE-Digital_record-concerns-support-trusts" /o:"dfe-digital" /d:sonar.token="${{ secrets.SONAR_TOKEN }}" /d:sonar.host.url="https://sonarcloud.io" /d:sonar.coverageReportPaths=./ConcernsCaseWork/CoverageReport/SonarQube.xml
          dotnet build ConcernsCaseWork/ConcernsCaseWork.sln
          dotnet test ConcernsCaseWork/ConcernsCaseWork.sln --no-build --verbosity normal --collect:"XPlat Code Coverage"
          reportgenerator -reports:"./**/coverage.cobertura.xml" -targetdir:./ConcernsCaseWork/CoverageReport -reporttypes:SonarQube
          dotnet-sonarscanner end /d:sonar.token="${{ secrets.SONAR_TOKEN }}"

      - name: Stop Redis
        if: always()
        run: docker stop redis
