name: Cypress test linting

on:
  pull_request:
    paths:
      - ConcernsCaseWork/ConcernsCaseWork.CypressTests/**/*
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        # Updated to latest v4 SHA
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
      - name: lint cypress tests
        working-directory: ConcernsCaseWork/ConcernsCaseWork.CypressTests
        run: |
          npm ci
          npm run lint        
