name: Run Docker tests

on:
  push:
    branches: main
  pull_request:
    paths:
      - Dockerfile
    types: [opened, synchronize]

jobs:
  scan:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        stage: [
          "final",
          "initcontainer"
        ]
    outputs:
      image: ${{ steps.build.outputs.imageid }}
    steps:
      - name: Checkout code
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@22b48a429f10e1de233237b5c534c9c3d2e41597

      - name: Build Docker image
        uses: docker/build-push-action@7b93b2b85cab035420f0625ccc86452575bab2be
        id: build
        with:
          secrets: github_token=${{ secrets.GITHUB_TOKEN }}
          load: true
          cache-from: type=gha
          cache-to: type=gha
          target: ${{ matrix.stage }}
          push: false

      - name: Export docker image as tar
        run: docker save -o ${{ matrix.stage }}.tar ${{ steps.build.outputs.imageid }}
