name: Run Docker tests

on:
  push:
    branches: main
  pull_request:
    paths:
      - Dockerfile
    types: [opened, synchronize]

jobs:
  scan:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        stage: [
          "final",
          "initcontainer"
        ]
    outputs:
      image: ${{ steps.build.outputs.imageid }}
    steps:
      - name: Checkout code
        # Updated to latest v5 SHA
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8

      - name: Set up Docker Buildx
        # Updated to latest v3 SHA
        uses: docker/setup-buildx-action@b5ca514842bbda0d7c86c1e96d5c4c7fc297ef53

      - name: Build Docker image
        # Updated to latest v4 SHA
        uses: docker/build-push-action@d08e5c3acec8b8b9dfc9e5f30b1a8b0a07d35e1d
        id: build
        with:
          secrets: github_token=${{ secrets.GITHUB_TOKEN }}
          load: true
          cache-from: type=gha
          cache-to: type=gha
          target: ${{ matrix.stage }}
          push: false

      - name: Export docker image as tar
        run: docker save -o ${{ matrix.stage }}.tar ${{ steps.build.outputs.imageid }}
