name: Run Docker tests

on:
  push:
    branches: main
  pull_request:
    paths:
      - Dockerfile
    types: [opened, synchronize]

jobs:
  scan:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        stage: [
          "final",
          "initcontainer"
        ]
    outputs:
      image: ${{ steps.build.outputs.imageid }}
    steps:
      - name: Checkout code
        # Updated to latest v4 SHA
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        # Updated to latest v4 SHA
        uses: docker/setup-buildx-action@f7ce87c531ee0303fd7a9c7d2f21786dca876008 # v4.0.0

      - name: Build Docker image
        # Updated to latest v4 SHA
        uses: docker/build-push-action@v7
        id: build
        with:
          secrets: github_token=${{ secrets.GITHUB_TOKEN }}
          load: true
          cache-from: type=gha
          cache-to: type=gha
          target: ${{ matrix.stage }}
          push: false

      - name: Export docker image as tar
        run: docker save -o ${{ matrix.stage }}.tar ${{ steps.build.outputs.imageid }}
