name: Run UI automation

on:
  push:
    branches:
    - develop
  pull_request:
    branches: [ develop ]
    types: [ opened, synchronize, reopened ]

jobs:
  run-ui-automation:
    runs-on: ubuntu-latest
    environment: dev

    services:
      sql-server:
        image: mcr.microsoft.com/mssql/server:2017-latest
        ports:
        - 1433:1433
        environment:
          ACCEPT_EULA: "Y"
          SA_PASSWORD: "change_this_password"

    # steps:
    #   - name: Running SQL Server image
    #   run: echo hello world
    #   #run: docker run -e "ACCEPT_EULA=Y" -e "MSSQL_SA_PASSWORD=change_this_password" -p 1433:1433 -d mcr.microsoft.com/mssql/server:2017-latest
