name: Run UI automation

on:
  push:
    branches:
    - develop
  pull_request:
    branches: [ develop ]
    types: [ opened, synchronize, reopened ]

jobs:
  run-ui-automation:
    runs-on: ubuntu-latest
    environment: dev

    services:
      sql-server:
        image: mcr.microsoft.com/mssql/server:2017-latest
        ports:
        - 1433:1433
        env:
          ACCEPT_EULA: "Y"
          SA_PASSWORD: "change_this_password"

      redis:
        image: redis:alpine
        ports:
        - 6379:6379
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x

      - name: Restore dependencies
        run: dotnet restore ConcernsCaseWork/ConcernsCaseWork.sln

      - name: Build application
        run: dotnet build ConcernsCaseWork/ConcernsCaseWork.sln

      - name: Configure application
        run: |
          dotnet user-secrets set "VCAP_SERVICES" "{'redis': [{'credentials': {'host': '127.0.0.1','password': 'password','port': '6379','tls_enabled': 'false'}}]}"
          dotnet user-secrets set "trams:api_key" "app-key"
          dotnet user-secrets set "trams:api_endpoint" "https://trams-external-api.azurewebsites.net"
          dotnet user-secrets set "ConnectionStrings:DefaultConnection" "Server=localhost,1433;Database=sip;Integrated Security=true;TrustServerCertificate=True"
          dotnet user-secrets set "ConcernsCaseworkApi:ApiKeys" "app-key"
          dotnet user-secrets set "ConcernsCasework:ApiKey" "app-key"
          dotnet user-secrets set "ConcernsCasework:ApiEndpoint" "https://localhost"

      - name: Run application
        run: dotnet run --project ConcernsCaseWork/ConcernsCaseWork/ConcernsCaseWork.csproj